{{- if .Values.global.gateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.global.gateway.name }}
  namespace: {{ .Values.global.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.global.gateway.gatewayclass.name }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.global.certificate.secretName }}
      allowedRoutes:
        namespaces:
          from: All
{{- end }}
