apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AayushChauhan1916/two-tier-k8-deployment-with-argo-cd
    targetRevision: main
    path: infra
    helm:
      valueFiles:
        - ../constants/production/common.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
