apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}

  hostnames:
{{- range .Values.hostnames }}
    - {{ . | quote }}
{{- end }}

  rules:
    - backendRefs:
        - name: {{ include "chart.appServiceName" . }}
          port: {{ .Values.service.port }}
