apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name:  {{ include "chart.fullname" . }}-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "chart.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.secrets.jwtSecretKey }}
