apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  parentRefs:
    - name: {{ .Values.global.gateway.name }}
      namespace: {{ .Values.global.gateway.namespace }}

  hostnames:
    {{- if .Values.hostnames }}
{{- range .Values.hostnames }}
    - {{ . | quote }}
{{- end }}
    {{- else }}
    # Add service-specific hostnames if needed
{{- end }}

  rules:
    - backendRefs:
        - name: {{ include "chart.apiServiceName" . }}
          port: {{ .Values.service.port }}
