apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway-system

  hostnames:
  - argo.cardflex.in

  rules:
  - backendRefs:
    - name: argocd-server
      port: 80
