apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
  - name: {{ .Values.global.gateway.name }}
    namespace: {{ .Values.global.gateway.namespace }}

  hostnames:
  - argo.cardflex.in

  rules:
  - backendRefs:
    - name: argocd-server
      port: 80
