{{- if .Values.global.certificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.certificate.name }}
  namespace: {{ .Values.global.certificate.namespace }}
spec:
  secretName: {{ .Values.global.certificate.secretName }}

  issuerRef:
    name: {{ .Values.global.certificate.issuerRef.name }}
    kind: {{ .Values.global.certificate.issuerRef.kind }}

  dnsNames:
{{- range .Values.global.certificate.dnsNames }}
    - {{ . }}
{{- end }}
{{- end }}
